CREATE TABLE public.tb01_usuario (
    usuarioid bigint generated by default as identity,
    nome varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    login varchar(100) NOT NULL,
    senha varchar(255) NOT NULL,
    CONSTRAINT tb01_usuarioid_pk PRIMARY KEY (usuarioid)
);
